version: '2'
services:
  # To run benchmark suite docker-compose run --rm php src/benchmark
  php:
    image: prooph/php:7.2-zts
    environment:
      DRIVER: "arangodb"
      PHP_IDE_CONFIG: "serverName=application"
      ARANGODB_HOST: "tcp://arangodb:8529"
      ARANGODB_USERNAME: ""
      ARANGODB_PASSWORD: ""
      ARANGODB_DB: _system
    volumes:
      - "./:/app"

  arangodb:
    image: arangodb:3.2.0
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
